name: Auto-Merge HZN to DEV

on:
  push:
    branches: ["HZN"]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Merge HZN into DEV
        run: |
          git checkout HZN
          git fetch DEV
          git pull origin HZN
          git merge DEV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}