name: Auto-Merge HZN to DEV

on:
  push:
    branches: ["HZN"]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Merge master back to dev
        run: |
          git fetch --unshallow
          git checkout HZN
          git pull
          git merge --no-ff origin/DEV -m "Auto-merge master back to dev"
          git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}