# This is a basic workflow to help you get started with Actions

name: Auto-Merge HZN to DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - "HZN" 

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge HZN -> DEV
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: HZN
          target_branch: DEV
          github_token: ${{ secrets.GITHUB_TOKEN }}