name: Auto-Merge HZN to DEV

on:
  push:
    branches: ["HZN"]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Merge master back to dev
        run: |
          git fetch --unshallow
          git checkout HZN
          git pull
          git merge --no-ff DEV -m "Auto-merge master back to dev"
          git push