name: Auto Merge HZN to Dev

on:
  push:
    branches:
      - HZN

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Merge HZN into Dev
        run: |
          git checkout DEV
          git pull
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
