name: Merge branch HZN to DEV
on:
  push:
    branches:
      - 'HZN'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge HZN -> DEV
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: DEV
          message: Merge ZHN into DEV
          github_token: ${{ secrets.GITHUB_TOKEN }}
